[package]
name = "amdgpu_top"
version = "0.1.4"
edition = "2021"
license = "MIT"
homepage = "https://github.com/Umio-Yasuno/amdgpu_top"
authors = ["Umio Yasuno <coelacanth_dream@proton.me>"]
description = """
Tool to displays AMDGPU usage.
The tool displays information gathered from performance counters (GRBM, GRBM2), sensors, fdinfo, gpu_metrics and AMDGPU driver.
"""

[features]
default = ["fdinfo"]
fdinfo = []

[[bin]]
name = "amdgpu_top"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libdrm_amdgpu_sys = { git = "https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs" }
cursive = { version = "0.20", default-features = false, features = ["crossterm-backend"] }
ctrlc = { version = "3.2.5" }
serde_json = { version = "1.0.*" }

[profile.release]
opt-level = 2
strip = true
lto = true
codegen-units = 1

# cargo-deb
[package.metadata.deb]
depends = "libc6, libgcc-s1, libdrm2, libdrm-amdgpu1"
section = "utils"
